spring.application.name=todo-api
server.port=${PORT:8080}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized

info.app.name=todo-api
info.app.description=Spring Boot Todo API deployed on Amazon EC2
info.app.java.version=${java.version}
