spring.application.name=file-upload-service
server.port=${PORT:8080}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

management.endpoints.web.exposure.include=health,info

app.aws.region=${AWS_REGION:us-east-1}
app.s3.bucket-name=${APP_S3_BUCKET_NAME:replace-me}
app.s3.presign-duration=15m
